added feature for creating schema
NoRage28/FakeService pull request #1
Opened 2023-02-10 07:46 UTC by NoRage28

2023-02-10 07:48 UTC, bakarovroman requested changes
one pull request, one migrations file

2023-02-10 07:51 UTC, bakarovroman commented on fake_service/dataset/tests.py
> +# Create your tests here.
tests?

2023-02-10 07:53 UTC, bakarovroman commented on fake_service/dataset/views.py
> +    serializer_class = CreateSchemaSerializer
use 
```
    def get_serializer_class(self):
        serializers = {
            "create": CreateSchemaSerializer,
        }
        return serializers.get(self.action)
```

2023-02-10 07:58 UTC, 250kgBeast commented on fake_service/dataset/serializers.py
> +        return instance
I think [model serializer](https://www.django-rest-framework.org/api-guide/serializers/#modelserializer) may be used here

2023-02-10 07:59 UTC, 250kgBeast commented on fake_service/dataset/tests.py
> +# Create your tests here.
tests?

2023-02-12 10:50 UTC, 250kgBeast commented on fake_service/dataset/serializers.py
> +class CreateSchemaSerializer(serializers.ModelSerializer):
rename to SchemaSerializer

2023-02-12 11:00 UTC, 250kgBeast commented on fake_service/dataset/tests/test_schema.py
> +        self.assertEqual(result[0]['columns'], self.columns_data)
for key, value in result.items():
   self.assertEqual(getattr(self.schema, key), value)

2023-02-12 11:06 UTC, 250kgBeast commented on fake_service/dataset/tests/test_schema.py
> +        self.assertEqual(Schema.objects.last().title, 'Schema_2')
created_schema = Schema.objects.last()
for key, value in data.items():
    self.assertEqual(getattr(created_schema, key), value)

2023-02-13 08:34 UTC, merged